name: prg-rents
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.2
  - pip=20.0.2
  - beautifulsoup4=4.8.2
  - blinker=1.4
  - pyyaml=5.3.1
  - requests=2.23.0
  - mongoengine=0.20.0
  - pymongo=3.9.0
  - pip:
     - dacite==1.5.1